name: Build and Deploy Docs
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
jobs:
  build-and-deploy-doc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - shell: bash
      run: pwd
    - name: Vuepress Deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_REPO: ralcorta/afip.ts
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: npm i && npm run docs:build
        BUILD_DIR: ./docs/.vuepress/dist
        CNAME: https://www.afipts.com
        