name: Build and Deploy Docs
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
jobs:
  build-and-deploy-doc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        registry-url: https://registry.npmjs.org/
        node-version: '16.10.0'
    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_REPO: valiulab/afip.ts
        TARGET_BRANCH: main
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist
        CNAME: https://afip.js